college:
  info:
    base-package: college

logging:
  level:
    college.order: INFO
spring:
  cloud:
    # Spring Cloud Gateway 配置项，对应 GatewayProperties 类
    gateway:
      # 路由配置项，对应 RouteDefinition 数组
      routes:
        - id: netty
          uri: lb:ws://netty-server
          predicates:
            - Path=/ws/**

        ## system-server 服务
        - id: order-center-api # 路由的编号
          uri: lb://order-center
          predicates: # 断言，作为路由的匹配条件，对应 RouteDefinition 数组
            - Path=/admin-api/order/**
          filters:
            - RewritePath=/admin-api/system/v3/api-docs, /v3/api-docs # 配置，保证转发到 /v3/api-docs