college:
  info:
    base-package: college

rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: sample_producer_group
    send-message-timeout: 30000
  consumer:
    group: sample_consumer_group